server:
  port: 9000
  servlet:
    context-path: /friendboy

cloud:
  aws:
    s3:
      bucket: k8b301-bucket
    credentials:
      access-key: AKIAY7TIHYUIKEQBZTE2
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  data:
    mongodb:
      host: 3.35.18.146
      port: 27017
      authentication-database: admin
      database: some
      username: some
      password: '!23Qwe'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://3.35.18.146:3306/some?serverTimezone=UTC&characterEncoding=UTF-8
    username: some
    password: '!23Qwe'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  redis:
    host: 3.35.18.146
    port: 6379
    password: '13524'
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
